# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

	lane :beta do
	  match(
            readonly: is_ci
          )
	  increment_build_number(
	    xcodeproj: "Questo.xcodeproj"
	  )
          build_app(scheme: "Questo",
                    export_xcargs: "-allowProvisioningUpdates",
		    workspace: "Questo.xcworkspace")
  	  upload_to_testflight(
            skip_waiting_for_build_processing: true,
            apple_id: "1183390727"
          )
	end
	desc "Push a new release build to the App Store"
	lane :release do
	  # Ensure that your git status is not dirty
	ensure_git_status_clean

	# Increment the build number (not the version number)
	# Providing the xcodeproj is optional
	increment_build_number(xcodeproj: "Questo.xcodeproj")

	# Commit the version bump
	commit_version_bump(xcodeproj: "Questo.xcodeproj")

	# Add a git tag for this build. This will automatically
	# use an appropriate git tag name
	add_git_tag

	# Push the new commit and tag back to your git remote
	push_to_git_remote
    build_app(workspace: "Questo.xcworkspace", scheme: "Questo")
    upload_to_app_store
    slack(message: "Successfully distributed a new build")
  end
end
